# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home1/dilawars/Work/GITHUB/BhallaLab/moogli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home1/dilawars/Work/GITHUB/BhallaLab/moogli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home1/dilawars/Work/GITHUB/BhallaLab/moogli/CMakeFiles /home1/dilawars/Work/GITHUB/BhallaLab/moogli/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home1/dilawars/Work/GITHUB/BhallaLab/moogli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _moogli

# Build rule for target.
_moogli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _moogli
.PHONY : _moogli

# fast build rule for target.
_moogli/fast:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/build
.PHONY : _moogli/fast

#=============================================================================
# Target rules for targets named sip

# Build rule for target.
sip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sip
.PHONY : sip

# fast build rule for target.
sip/fast:
	$(MAKE) -f moogli/bin/sip/CMakeFiles/sip.dir/build.make moogli/bin/sip/CMakeFiles/sip.dir/build
.PHONY : sip/fast

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f moogli/bin/src/CMakeFiles/src.dir/build.make moogli/bin/src/CMakeFiles/src.dir/build
.PHONY : src/fast

moogli/bin/moc/NetworkViewer.moc.o: moogli/bin/moc/NetworkViewer.moc.cpp.o
.PHONY : moogli/bin/moc/NetworkViewer.moc.o

# target to build an object file
moogli/bin/moc/NetworkViewer.moc.cpp.o:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/moogli/bin/moc/NetworkViewer.moc.cpp.o
.PHONY : moogli/bin/moc/NetworkViewer.moc.cpp.o

moogli/bin/moc/NetworkViewer.moc.i: moogli/bin/moc/NetworkViewer.moc.cpp.i
.PHONY : moogli/bin/moc/NetworkViewer.moc.i

# target to preprocess a source file
moogli/bin/moc/NetworkViewer.moc.cpp.i:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/moogli/bin/moc/NetworkViewer.moc.cpp.i
.PHONY : moogli/bin/moc/NetworkViewer.moc.cpp.i

moogli/bin/moc/NetworkViewer.moc.s: moogli/bin/moc/NetworkViewer.moc.cpp.s
.PHONY : moogli/bin/moc/NetworkViewer.moc.s

# target to generate assembly for a file
moogli/bin/moc/NetworkViewer.moc.cpp.s:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/moogli/bin/moc/NetworkViewer.moc.cpp.s
.PHONY : moogli/bin/moc/NetworkViewer.moc.cpp.s

moogli/bin/moc/Viewer.moc.o: moogli/bin/moc/Viewer.moc.cpp.o
.PHONY : moogli/bin/moc/Viewer.moc.o

# target to build an object file
moogli/bin/moc/Viewer.moc.cpp.o:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/moogli/bin/moc/Viewer.moc.cpp.o
.PHONY : moogli/bin/moc/Viewer.moc.cpp.o

moogli/bin/moc/Viewer.moc.i: moogli/bin/moc/Viewer.moc.cpp.i
.PHONY : moogli/bin/moc/Viewer.moc.i

# target to preprocess a source file
moogli/bin/moc/Viewer.moc.cpp.i:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/moogli/bin/moc/Viewer.moc.cpp.i
.PHONY : moogli/bin/moc/Viewer.moc.cpp.i

moogli/bin/moc/Viewer.moc.s: moogli/bin/moc/Viewer.moc.cpp.s
.PHONY : moogli/bin/moc/Viewer.moc.s

# target to generate assembly for a file
moogli/bin/moc/Viewer.moc.cpp.s:
	$(MAKE) -f CMakeFiles/_moogli.dir/build.make CMakeFiles/_moogli.dir/moogli/bin/moc/Viewer.moc.cpp.s
.PHONY : moogli/bin/moc/Viewer.moc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... _moogli"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sip"
	@echo "... src"
	@echo "... moogli/bin/moc/NetworkViewer.moc.o"
	@echo "... moogli/bin/moc/NetworkViewer.moc.i"
	@echo "... moogli/bin/moc/NetworkViewer.moc.s"
	@echo "... moogli/bin/moc/Viewer.moc.o"
	@echo "... moogli/bin/moc/Viewer.moc.i"
	@echo "... moogli/bin/moc/Viewer.moc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

